openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Empleados
  description: Operaciones relacionadas con empleados
paths:
  /api/empleado/{id}:
    get:
      tags:
      - Empleados
      summary: Ver un empleado
      operationId: getById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Empleado'
    put:
      tags:
      - Empleados
      summary: Actualizar un empelado
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Empleado'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Empleado'
    delete:
      tags:
      - Empleados
      summary: Eliminar un empelado
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/empleado:
    get:
      tags:
      - Empleados
      summary: Listar todos los empleados
      operationId: getAll
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Empleado'
    post:
      tags:
      - Empleados
      summary: Ingresar un empelado
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmpleadoDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Empleado'
components:
  schemas:
    Empleado:
      type: object
      properties:
        id:
          type: integer
          format: int64
        dni:
          type: integer
          format: int64
        nombre:
          type: string
        apellido:
          type: string
        telefono:
          type: string
        provincia:
          type: string
        localidad:
          type: string
        genero:
          type: string
        legajo:
          type: integer
          format: int32
        cargo:
          type: string
        salario:
          type: number
          format: double
        activo:
          type: boolean
        fechaIngreso:
          type: string
          format: date
        fechaEgreso:
          type: string
          format: date
    EmpleadoDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        dni:
          type: integer
          format: int64
        nombre:
          type: string
        apellido:
          type: string
        telefono:
          type: string
        provincia:
          type: string
        localidad:
          type: string
        genero:
          type: string
        legajo:
          type: integer
          format: int32
        cargo:
          type: string
        salario:
          type: number
          format: double
        activo:
          type: boolean
        fechaIngreso:
          type: string
          format: date
        fechaEgreso:
          type: string
          format: date
